# Generated by Django 3.2.8 on 2021-11-14 23:21

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'campus',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coordinator')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=20)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.campus')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Student_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.team')),
            ],
            options={
                'db_table': 'student_team',
            },
        ),
        migrations.CreateModel(
            name='Student_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.report')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'db_table': 'student_report',
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=6)),
                ('teaching_period', models.CharField(max_length=8)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campus')),
                ('coordinator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.coordinator')),
            ],
            options={
                'db_table': 'offering',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to=dashboard.models.user_directory_path)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('DD', 'Declaration of Deliverables'), ('AS', 'Weekly Activity sheet'), ('SS', 'Excel sheet of all students')], max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.offering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'db_table': 'enrolment',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1200)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField()),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coordinator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'db_table': 'alert',
            },
        ),
    ]
