# Generated by Django 3.2.9 on 2021-11-18 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_student_user'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_report',
            name='report',
        ),
        migrations.RemoveField(
            model_name='student_report',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student_team',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student_team',
            name='team',
        ),
        migrations.AddField(
            model_name='offering',
            name='students',
            field=models.ManyToManyField(to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='offering',
            name='year',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='students',
            field=models.ManyToManyField(to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(to='accounts.Student'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.coordinator'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offering',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='dashboard.campus'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='coordinator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='accounts.coordinator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offering',
            name='teaching_period',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='report',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='accounts.coordinator'),
        ),
        migrations.AlterField(
            model_name='team',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='dashboard.campus'),
        ),
        migrations.DeleteModel(
            name='Enrolment',
        ),
        migrations.DeleteModel(
            name='Student_Report',
        ),
        migrations.DeleteModel(
            name='Student_Team',
        ),
    ]
