# Generated by Django 3.2.9 on 2021-11-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211118_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offering',
            old_name='coordinator_id',
            new_name='coordinator',
        ),
    ]
