# Generated by Django 3.2.9 on 2021-11-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_coordinator_id_offering_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='dashboard.offering'),
        ),
    ]
