# Generated by Django 3.2.9 on 2021-11-29 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alert_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.alert'),
            preserve_default=False,
        ),
    ]
