# Generated by Django 3.2.9 on 2021-11-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211129_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alert',
            new_name='body',
        ),
    ]
