# Generated by Django 3.2.9 on 2021-11-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_team_students'),
        ('accounts', '0005_auto_20211119_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='dashboard.team'),
            preserve_default=False,
        ),
    ]
