# Generated by Django 3.2.9 on 2021-11-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
