# Generated by Django 3.2.8 on 2021-11-14 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_survey',
            old_name='form',
            new_name='survey',
        ),
        migrations.AlterModelTable(
            name='question_survey',
            table='question_survey',
        ),
        migrations.AlterModelTable(
            name='survey',
            table='survey',
        ),
    ]
