# Generated by Django 3.2.8 on 2021-11-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20211115_0323'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
