# Generated by Django 3.2.9 on 2021-11-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20211125_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='survey.survey'),
            preserve_default=False,
        ),
    ]
