# Generated by Django 3.2.9 on 2021-11-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_question_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weighting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
