# Generated by Django 3.2.9 on 2021-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_question_weighting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='evaluation_type',
            field=models.CharField(choices=[('S', 'Self Evaluation'), ('P', 'Peer Evaluation')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('C', 'Comment Question'), ('R', 'Rating Question')], max_length=1),
        ),
    ]
