# Generated by Django 3.2.9 on 2021-11-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_alert_alert_body'),
        ('survey', '0005_alter_submission_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='offerings',
            field=models.ManyToManyField(to='dashboard.Offering'),
        ),
    ]
