# Generated by Django 3.2.9 on 2021-11-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_user'),
        ('survey', '0005_auto_20211117_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_survey',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question_survey',
            name='survey',
        ),
        migrations.AddField(
            model_name='submission',
            name='evaluations',
            field=models.ManyToManyField(to='survey.Evaluation'),
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='survey.evaluation'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='survey.question'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='survey.evaluation'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='survey.question'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='accounts.coordinator'),
        ),
        migrations.DeleteModel(
            name='Evaluation_Submission',
        ),
        migrations.DeleteModel(
            name='Question_Survey',
        ),
    ]
