# Generated by Django 3.2.9 on 2021-11-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211130_1025'),
        ('survey', '0006_survey_offerings'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='offerings',
            field=models.ManyToManyField(related_name='surveys', to='dashboard.Offering'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(related_name='surveys', to='survey.Question'),
        ),
    ]
