# Generated by Django 3.2.9 on 2021-11-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20211118_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='spe_number',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
    ]
