# Generated by Django 3.2.9 on 2021-12-01 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_evaluation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(null=True)),
                ('comment', models.CharField(max_length=1200, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='survey.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='survey.question')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.RemoveField(
            model_name='rating',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='question',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
