# Generated by Django 3.2.9 on 2021-11-23 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211119_1321'),
        ('survey', '0009_submission_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='evaluatee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_by_peers', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_by_student', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.student'),
        ),
    ]
